CREATE SCHEMA IF NOT EXISTS USERSDB;

USE USERSDB;

CREATE TABLE IF NOT EXISTS SMARTJOB_USER (
  ID INT NOT NULL auto_increment,
  NAME VARCHAR(120) NOT NULL,
  PASSWORD LONGTEXT NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,  
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  LAST_LOGIN TIMESTAMP,
  TOKEN VARCHAR(1000),
  ISACTIVE TINYINT NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS USER_PHONE (
  ID INT NOT NULL auto_increment,
  PHONE_NUMBER VARCHAR(15) NOT NULL,
  CITY_CODE VARCHAR(1) NOT NULL,
  COUNTRY_CODE VARCHAR(2) NOT NULL,
  USER_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) references SMARTJOB_USER(ID)
);


CREATE TABLE IF NOT EXISTS SMARTJOB_ROLE (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(120) NOT NULL,
  PRIMARY KEY (ID));

INSERT INTO SMARTJOB_ROLE(NAME) VALUES('SMARTJOB_USER_ROLE');

CREATE TABLE IF NOT EXISTS USER_ROLE (
  USER_ID INT NOT NULL,
  ROLE_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) references SMARTJOB_USER(ID),
  FOREIGN KEY (ROLE_ID) references SMARTJOB_ROLE(ID));
 
CREATE UNIQUE INDEX PK_USER_ROLE ON USER_ROLE(USER_ID, ROLE_ID);

